version: '3'

services:
  proxpi:
    container_name: proxpi
    image: epicwink/proxpi:latest
    volumes:
      - ./proxpi/cache:/var/cache/proxpi
    environment:
      - PROXPI_CACHE_DIR=/var/cache/proxpi
    networks:
      - pacnet

  pacoloco:
    container_name: pacoloco
    image: ghcr.io/anatol/pacoloco
    volumes:
      - ./pacoloco/cache:/var/cache/pacoloco
      - ./pacoloco/pacoloco.yaml:/etc/pacoloco.yaml
    networks:
      - pacnet

  builder:
    build: ./builder
    image: archiso-builder
    privileged: true
    networks:
      - pacnet
    depends_on:
      - pacoloco
      - proxpi

networks:
  pacnet:
